### ISSUE TITLE
No such file or directory '../themes/void.css'

### ISSUE THREAD

**Issue by DoubleClick7** [Paul-Houser/StartTree#7]
On running './generate.py', it gives:
Traceback (most recent call last):
  File "./generate.py", line 137, in <module>
    main()
  File "./generate.py", line 133, in main
    gen_style(file_dict)
  File "./generate.py", line 120, in gen_style
    copyfile(theme, home + '/.cache/StartTree/styles/colors.css')
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../themes/void.css'

**Comment by Paul-Houser** [comment]
Just pushed a fix, pull it and give it another shot. Let me know if it's indeed fixed for you so I can mark this issue as closed.
